//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOK.MissionControl.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HOK.MissionControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на f4621647-f928-422a-8afa-e08293305ec8.
        /// </summary>
        internal static string CommunicatorGuid {
            get {
                return ResourceManager.GetString("CommunicatorGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 56603be6-aeb2-45d0-9ebc-2830fad6368b.
        /// </summary>
        internal static string HealthReportTrackerGuid {
            get {
                return ResourceManager.GetString("HealthReportTrackerGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 90391154-67BB-452E-A1A7-A07A98B94F86.
        /// </summary>
        internal static string LinkUnloadTrackerGuid {
            get {
                return ResourceManager.GetString("LinkUnloadTrackerGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HOK.MissionControl.addin.
        /// </summary>
        internal static string MissionControl_AddinName {
            get {
                return ResourceManager.GetString("MissionControl_AddinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Communicator_Command;WebsiteLink_Command.
        /// </summary>
        internal static string MissionControl_AdditionalButtons {
            get {
                return ResourceManager.GetString("MissionControl_AdditionalButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This plug-in allows Design Technology Group to collect valuable information about the model and its contents that are then reported back to the user via online dashboard..
        /// </summary>
        internal static string MissionControl_Desc {
            get {
                return ResourceManager.GetString("MissionControl_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на missionControl_32x32.png.
        /// </summary>
        internal static string MissionControl_ImageName {
            get {
                return ResourceManager.GetString("MissionControl_ImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mission Control.
        /// </summary>
        internal static string MissionControl_Name {
            get {
                return ResourceManager.GetString("MissionControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HOK.MissionControl.
        /// </summary>
        internal static string MissionControl_Namespace {
            get {
                return ResourceManager.GetString("MissionControl_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mission Control.
        /// </summary>
        internal static string MissionControl_PanelName {
            get {
                return ResourceManager.GetString("MissionControl_PanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 32d44b45-7bf6-49f1-9b81-f41ae929cfcb.
        /// </summary>
        internal static string SharedParameterTrackerGuid {
            get {
                return ResourceManager.GetString("SharedParameterTrackerGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0504A758-BF15-4C90-B996-A795D92B42DB.
        /// </summary>
        internal static string SheetsTrackerGuid {
            get {
                return ResourceManager.GetString("SheetsTrackerGuid", resourceCulture);
            }
        }
    }
}
